import 'dart:math';

import 'package:currency_formatter/currency_formatter.dart';

enum Currency {
  clp(
    symbol: 'CL\$',
    symbolNative: '\$',
    decimalDigits: 0,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 152,
    isoLetters: 'CLP',
    isoDigits: 0,
  ),
  usd(
    symbol: '\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 840,
    isoLetters: 'USD',
    isoDigits: 2,
  ),
  aed(
    symbol: 'د.إ.',
    symbolNative: 'د.إ.',
    decimalDigits: 2,
    majorSingle: 'Dirham',
    majorPlural: 'Dirhams',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 784,
    isoLetters: 'AED',
    isoDigits: 2,
  ),
  afn(
    symbol: 'Af',
    symbolNative: '؋',
    decimalDigits: 2,
    majorSingle: 'Afghani',
    majorPlural: 'Afghani',
    minorSingle: 'Pul',
    minorPlural: 'Pul',
    isoNum: 971,
    isoLetters: 'AFN',
    isoDigits: 2,
  ),
  all(
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    majorSingle: 'Lek',
    majorPlural: 'Lekë',
    minorSingle: 'Qindarka',
    minorPlural: 'Qindarka',
    isoNum: 8,
    isoLetters: 'ALL',
    isoDigits: 2,
  ),
  amd(
    symbol: '֏',
    symbolNative: 'դր',
    decimalDigits: 2,
    majorSingle: 'Dram',
    majorPlural: 'Dram',
    minorSingle: 'Luma',
    minorPlural: 'Luma',
    isoNum: 51,
    isoLetters: 'AMD',
    isoDigits: 2,
  ),
  ang(
    symbol: 'ƒ',
    symbolNative: 'ƒ',
    decimalDigits: 2,
    majorSingle: 'Guilder',
    majorPlural: 'Guilders',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 532,
    isoLetters: 'ANG',
    isoDigits: 2,
  ),
  aoa(
    symbol: 'Kz',
    symbolNative: 'Kz',
    decimalDigits: 2,
    majorSingle: 'Kwanza',
    majorPlural: 'Kwanza',
    minorSingle: 'Centimo',
    minorPlural: 'Centimos',
    isoNum: 973,
    isoLetters: 'AOA',
    isoDigits: 2,
  ),
  ars(
    symbol: 'AR\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 32,
    isoLetters: 'ARS',
    isoDigits: 2,
  ),
  aud(
    symbol: 'AU\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 36,
    isoLetters: 'AUD',
    isoDigits: 2,
  ),
  awg(
    symbol: 'ƒ',
    symbolNative: 'ƒ',
    decimalDigits: 2,
    majorSingle: 'Florin',
    majorPlural: 'Florin',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 533,
    isoLetters: 'AWG',
    isoDigits: 2,
  ),
  azn(
    symbol: 'ман',
    symbolNative: '₼',
    decimalDigits: 2,
    majorSingle: 'Manat',
    majorPlural: 'Manat',
    minorSingle: 'Qapik',
    minorPlural: 'Qapik',
    isoNum: 944,
    isoLetters: 'AZN',
    isoDigits: 2,
  ),
  bam(
    symbol: 'KM',
    symbolNative: 'КМ',
    decimalDigits: 2,
    majorSingle: 'Convertible Mark',
    majorPlural: 'Marks',
    minorSingle: 'Fening',
    minorPlural: 'Fening',
    isoNum: 977,
    isoLetters: 'BAM',
    isoDigits: 2,
  ),
  bbd(
    symbol: 'BBD\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 52,
    isoLetters: 'BBD',
    isoDigits: 2,
  ),
  bdt(
    symbol: '৳',
    symbolNative: '৳',
    decimalDigits: 2,
    majorSingle: 'Taka',
    majorPlural: 'Taka',
    minorSingle: 'Poisha',
    minorPlural: 'Poisha',
    isoNum: 50,
    isoLetters: 'BDT',
    isoDigits: 2,
  ),
  bgn(
    symbol: 'лв.',
    symbolNative: 'лв.',
    decimalDigits: 2,
    majorSingle: 'Lev',
    majorPlural: 'Leva',
    minorSingle: 'Stotinka',
    minorPlural: 'Stotinki',
    isoNum: 975,
    isoLetters: 'BGN',
    isoDigits: 2,
  ),
  bhd(
    symbol: 'BD',
    symbolNative: 'د.ب.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 48,
    isoLetters: 'BHD',
    isoDigits: 3,
  ),
  bif(
    symbol: 'FBu',
    symbolNative: 'FBu',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 108,
    isoLetters: 'BIF',
    isoDigits: 0,
  ),
  bmd(
    symbol: '\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 60,
    isoLetters: 'BMD',
    isoDigits: 2,
  ),
  bnd(
    symbol: 'B\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 96,
    isoLetters: 'BND',
    isoDigits: 2,
  ),
  bob(
    symbol: 'Bs.',
    symbolNative: 'Bs.',
    decimalDigits: 2,
    majorSingle: 'Boliviano',
    majorPlural: 'Bolivianos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 68,
    isoLetters: 'BOB',
    isoDigits: 2,
  ),
  brl(
    symbol: 'R\$',
    symbolNative: 'R\$',
    decimalDigits: 2,
    majorSingle: 'Real',
    majorPlural: 'Reais',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 986,
    isoLetters: 'BRL',
    isoDigits: 2,
  ),
  bsd(
    symbol: '\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 44,
    isoLetters: 'BSD',
    isoDigits: 2,
  ),
  btn(
    symbol: 'Nu.',
    symbolNative: 'Nu.',
    decimalDigits: 2,
    majorSingle: 'Ngultrum',
    majorPlural: 'Ngultrums',
    minorSingle: 'Chetrum',
    minorPlural: 'Chetrums',
    isoNum: 64,
    isoLetters: 'BTN',
    isoDigits: 2,
  ),
  bwp(
    symbol: 'P',
    symbolNative: 'P',
    decimalDigits: 2,
    majorSingle: 'Pula',
    majorPlural: 'Pula',
    minorSingle: 'Thebe',
    minorPlural: 'Thebe',
    isoNum: 72,
    isoLetters: 'BWP',
    isoDigits: 2,
  ),
  byn(
    symbol: 'Br',
    symbolNative: 'руб.',
    decimalDigits: 2,
    majorSingle: 'Ruble',
    majorPlural: 'Rubles',
    minorSingle: 'Kapiejka',
    minorPlural: 'Kapiejka',
    isoNum: 933,
    isoLetters: 'BYN',
    isoDigits: 2,
  ),
  bzd(
    symbol: 'BZ\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 84,
    isoLetters: 'BZD',
    isoDigits: 2,
  ),
  cad(
    symbol: 'CA\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 124,
    isoLetters: 'CAD',
    isoDigits: 2,
  ),
  cdf(
    symbol: 'FC',
    symbolNative: '₣',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 976,
    isoLetters: 'CDF',
    isoDigits: 2,
  ),
  chf(
    symbol: 'Fr.',
    symbolNative: '₣',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 756,
    isoLetters: 'CHF',
    isoDigits: 2,
  ),
  ckd(
    symbol: '\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 0,
    isoLetters: 'CKD',
    isoDigits: 2,
  ),
  cny(
    symbol: 'CN¥',
    symbolNative: '¥元',
    decimalDigits: 2,
    majorSingle: 'Yuan',
    majorPlural: 'Yuan',
    minorSingle: 'Fen',
    minorPlural: 'Fen',
    isoNum: 156,
    isoLetters: 'CNY',
    isoDigits: 2,
  ),
  cop(
    symbol: 'CO\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 170,
    isoLetters: 'COP',
    isoDigits: 2,
  ),
  crc(
    symbol: '₡',
    symbolNative: '₡',
    decimalDigits: 2,
    majorSingle: 'Colón',
    majorPlural: 'Colones',
    minorSingle: 'Centimo',
    minorPlural: 'Centimos',
    isoNum: 188,
    isoLetters: 'CRC',
    isoDigits: 2,
  ),
  cuc(
    symbol: 'CUC\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 931,
    isoLetters: 'CUC',
    isoDigits: 2,
  ),
  cup(
    symbol: '\$MN',
    symbolNative: '₱',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 192,
    isoLetters: 'CUP',
    isoDigits: 2,
  ),
  cve(
    symbol: 'CV\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Escudo',
    majorPlural: 'Escudo',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 132,
    isoLetters: 'CVE',
    isoDigits: 2,
  ),
  czk(
    symbol: 'Kč',
    symbolNative: 'Kč',
    decimalDigits: 2,
    majorSingle: 'Koruna',
    majorPlural: 'Koruny',
    minorSingle: 'Haléř',
    minorPlural: 'Haléř',
    isoNum: 203,
    isoLetters: 'CZK',
    isoDigits: 2,
  ),
  djf(
    symbol: 'Fdj',
    symbolNative: 'ف.ج.',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 262,
    isoLetters: 'DJF',
    isoDigits: 0,
  ),
  dkk(
    symbol: 'kr.',
    symbolNative: 'kr.',
    decimalDigits: 2,
    majorSingle: 'Krone',
    majorPlural: 'Kroner',
    minorSingle: 'Øre',
    minorPlural: 'Øre',
    isoNum: 208,
    isoLetters: 'DKK',
    isoDigits: 2,
  ),
  dop(
    symbol: 'RD\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 214,
    isoLetters: 'DOP',
    isoDigits: 2,
  ),
  dzd(
    symbol: 'DA',
    symbolNative: 'د.ج.',
    decimalDigits: 2,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Santeem',
    minorPlural: 'Santeems',
    isoNum: 12,
    isoLetters: 'DZD',
    isoDigits: 2,
  ),
  egp(
    symbol: 'E£',
    symbolNative: 'ج.م.',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Qirsh',
    minorPlural: 'Qirsh',
    isoNum: 818,
    isoLetters: 'EGP',
    isoDigits: 2,
  ),
  ehp(
    symbol: 'Ptas.',
    symbolNative: 'Ptas.',
    decimalDigits: 2,
    majorSingle: 'Peseta',
    majorPlural: 'Pesetas',
    minorSingle: 'Céntimo',
    minorPlural: 'Céntimos',
    isoNum: 0,
    isoLetters: 'EHP',
    isoDigits: 2,
  ),
  ern(
    symbol: 'Nkf',
    symbolNative: 'ناكفا',
    decimalDigits: 2,
    majorSingle: 'Nakfa',
    majorPlural: 'Nakfa',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 232,
    isoLetters: 'ERN',
    isoDigits: 2,
  ),
  etb(
    symbol: 'Br',
    symbolNative: 'ብር',
    decimalDigits: 2,
    majorSingle: 'Birr',
    majorPlural: 'Birr',
    minorSingle: 'Santim',
    minorPlural: 'Santim',
    isoNum: 230,
    isoLetters: 'ETB',
    isoDigits: 2,
  ),
  eur(
    symbol: '€',
    symbolNative: '€',
    decimalDigits: 2,
    majorSingle: 'Euro',
    majorPlural: 'Euros',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 978,
    isoLetters: 'EUR',
    isoDigits: 2,
  ),
  fjd(
    symbol: 'FJ\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 242,
    isoLetters: 'FJD',
    isoDigits: 2,
  ),
  fkp(
    symbol: 'FK£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 238,
    isoLetters: 'FKP',
    isoDigits: 2,
  ),
  fok(
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    majorSingle: 'Króna',
    majorPlural: 'Krónas',
    minorSingle: 'Oyra',
    minorPlural: 'Oyra',
    isoNum: 0,
    isoLetters: 'FOK',
    isoDigits: 2,
  ),
  gbp(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 826,
    isoLetters: 'GBP',
    isoDigits: 2,
  ),
  gel(
    symbol: '₾',
    symbolNative: '₾',
    decimalDigits: 2,
    majorSingle: 'Lari',
    majorPlural: 'Lari',
    minorSingle: 'Tetri',
    minorPlural: 'Tetri',
    isoNum: 981,
    isoLetters: 'GEL',
    isoDigits: 2,
  ),
  ggp(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 0,
    isoLetters: 'GGP',
    isoDigits: 2,
  ),
  ghs(
    symbol: 'GH₵',
    symbolNative: '₵',
    decimalDigits: 2,
    majorSingle: 'Cedi',
    majorPlural: 'Cedis',
    minorSingle: 'Pesewa',
    minorPlural: 'Pesewas',
    isoNum: 936,
    isoLetters: 'GHS',
    isoDigits: 2,
  ),
  gip(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 292,
    isoLetters: 'GIP',
    isoDigits: 2,
  ),
  gmd(
    symbol: 'D',
    symbolNative: 'D',
    decimalDigits: 2,
    majorSingle: 'Dalasi',
    majorPlural: 'Dalasis',
    minorSingle: 'Butut',
    minorPlural: 'Bututs',
    isoNum: 270,
    isoLetters: 'GMD',
    isoDigits: 2,
  ),
  gnf(
    symbol: 'FG',
    symbolNative: 'FG',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 324,
    isoLetters: 'GNF',
    isoDigits: 0,
  ),
  gtq(
    symbol: 'Q',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Quetzal',
    majorPlural: 'Quetzales',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 320,
    isoLetters: 'GTQ',
    isoDigits: 2,
  ),
  gyd(
    symbol: 'G\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 328,
    isoLetters: 'GYD',
    isoDigits: 2,
  ),
  hkd(
    symbol: 'HK\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 344,
    isoLetters: 'HKD',
    isoDigits: 2,
  ),
  hnl(
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    majorSingle: 'Lempira',
    majorPlural: 'Lempiras',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 340,
    isoLetters: 'HNL',
    isoDigits: 2,
  ),
  hrk(
    symbol: 'kn',
    symbolNative: 'kn',
    decimalDigits: 2,
    majorSingle: 'Kuna',
    majorPlural: 'Kuna',
    minorSingle: 'Lipa',
    minorPlural: 'Lipa',
    isoNum: 191,
    isoLetters: 'HRK',
    isoDigits: 2,
  ),
  htg(
    symbol: 'G',
    symbolNative: 'G',
    decimalDigits: 2,
    majorSingle: 'Gourde',
    majorPlural: 'Gourdes',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 332,
    isoLetters: 'HTG',
    isoDigits: 2,
  ),
  huf(
    symbol: 'Ft',
    symbolNative: 'Ft',
    decimalDigits: 2,
    majorSingle: 'Forint',
    majorPlural: 'Forint',
    minorSingle: 'fillér',
    minorPlural: 'fillér',
    isoNum: 348,
    isoLetters: 'HUF',
    isoDigits: 2,
  ),
  idr(
    symbol: 'Rp',
    symbolNative: 'Rp',
    decimalDigits: 2,
    majorSingle: 'Rupiah',
    majorPlural: 'Rupiah',
    minorSingle: 'Sen',
    minorPlural: 'Sen',
    isoNum: 360,
    isoLetters: 'IDR',
    isoDigits: 2,
  ),
  ils(
    symbol: '₪',
    symbolNative: '₪',
    decimalDigits: 2,
    majorSingle: 'Shekel',
    majorPlural: 'Shekels',
    minorSingle: 'Agora',
    minorPlural: 'Agoras',
    isoNum: 376,
    isoLetters: 'ILS',
    isoDigits: 2,
  ),
  imp(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 0,
    isoLetters: 'IMP',
    isoDigits: 2,
  ),
  inr(
    symbol: 'Rs.',
    symbolNative: '₹',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Paisa',
    minorPlural: 'Paise',
    isoNum: 356,
    isoLetters: 'INR',
    isoDigits: 2,
  ),
  iqd(
    symbol: 'د.ع.',
    symbolNative: 'د.ع.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 368,
    isoLetters: 'IQD',
    isoDigits: 3,
  ),
  irr(
    symbol: '﷼',
    symbolNative: '﷼',
    decimalDigits: 2,
    majorSingle: 'Rial',
    majorPlural: 'Rials',
    minorSingle: 'Dinar',
    minorPlural: 'Dinars',
    isoNum: 364,
    isoLetters: 'IRR',
    isoDigits: 2,
  ),
  isk(
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    majorSingle: 'Krona',
    majorPlural: 'Krónur',
    minorSingle: 'Aurar',
    minorPlural: 'Aurar',
    isoNum: 352,
    isoLetters: 'ISK',
    isoDigits: 0,
  ),
  jep(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 0,
    isoLetters: 'JEP',
    isoDigits: 2,
  ),
  jmd(
    symbol: 'J\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 388,
    isoLetters: 'JMD',
    isoDigits: 2,
  ),
  jod(
    symbol: 'JD',
    symbolNative: 'د.أ.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 400,
    isoLetters: 'JOD',
    isoDigits: 3,
  ),
  jpy(
    symbol: '¥',
    symbolNative: '¥',
    decimalDigits: 2,
    majorSingle: 'Yen',
    majorPlural: 'Yen',
    minorSingle: 'Sen',
    minorPlural: 'Sen',
    isoNum: 392,
    isoLetters: 'JPY',
    isoDigits: 0,
  ),
  kes(
    symbol: 'KSh',
    symbolNative: 'KSh',
    decimalDigits: 2,
    majorSingle: 'Shilling',
    majorPlural: 'Shillings',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 404,
    isoLetters: 'KES',
    isoDigits: 2,
  ),
  kgs(
    symbol: 'с',
    symbolNative: 'с',
    decimalDigits: 2,
    majorSingle: 'Som',
    majorPlural: 'Som',
    minorSingle: 'Tyiyn',
    minorPlural: 'Tyiyn',
    isoNum: 417,
    isoLetters: 'KGS',
    isoDigits: 2,
  ),
  khr(
    symbol: '៛',
    symbolNative: '៛',
    decimalDigits: 2,
    majorSingle: 'Riel',
    majorPlural: 'Riels',
    minorSingle: 'Sen',
    minorPlural: 'Sen',
    isoNum: 116,
    isoLetters: 'KHR',
    isoDigits: 2,
  ),
  kid(
    symbol: '\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 0,
    isoLetters: 'KID',
    isoDigits: 2,
  ),
  kmf(
    symbol: 'CF',
    symbolNative: 'CF',
    decimalDigits: 2,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 174,
    isoLetters: 'KMF',
    isoDigits: 0,
  ),
  kpw(
    symbol: '₩',
    symbolNative: '₩',
    decimalDigits: 2,
    majorSingle: 'Won',
    majorPlural: 'Won',
    minorSingle: 'Chon',
    minorPlural: 'Chon',
    isoNum: 408,
    isoLetters: 'KPW',
    isoDigits: 2,
  ),
  krw(
    symbol: '₩',
    symbolNative: '₩',
    decimalDigits: 2,
    majorSingle: 'Won',
    majorPlural: 'Won',
    minorSingle: 'Jeon',
    minorPlural: 'Jeon',
    isoNum: 410,
    isoLetters: 'KRW',
    isoDigits: 0,
  ),
  kwd(
    symbol: 'KD',
    symbolNative: 'د.ك.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 414,
    isoLetters: 'KWD',
    isoDigits: 3,
  ),
  kyd(
    symbol: 'CI\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 136,
    isoLetters: 'KYD',
    isoDigits: 2,
  ),
  kzt(
    symbol: '₸',
    symbolNative: '₸',
    decimalDigits: 2,
    majorSingle: 'Tenge',
    majorPlural: 'Tenge',
    minorSingle: 'Tıyn',
    minorPlural: 'Tıyn',
    isoNum: 398,
    isoLetters: 'KZT',
    isoDigits: 2,
  ),
  lak(
    symbol: '₭N',
    symbolNative: '₭',
    decimalDigits: 2,
    majorSingle: 'Kip',
    majorPlural: 'Kip',
    minorSingle: 'Att',
    minorPlural: 'Att',
    isoNum: 418,
    isoLetters: 'LAK',
    isoDigits: 2,
  ),
  lbp(
    symbol: 'LL.',
    symbolNative: 'ل.ل.',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Qirsh',
    minorPlural: 'Qirsh',
    isoNum: 422,
    isoLetters: 'LBP',
    isoDigits: 2,
  ),
  lkr(
    symbol: 'Rs.',
    symbolNative: 'රු or ரூ',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 144,
    isoLetters: 'LKR',
    isoDigits: 2,
  ),
  lrd(
    symbol: 'L\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 430,
    isoLetters: 'LRD',
    isoDigits: 2,
  ),
  lsl(
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    majorSingle: 'Loti',
    majorPlural: 'maLoti',
    minorSingle: 'Sente',
    minorPlural: 'Lisente',
    isoNum: 426,
    isoLetters: 'LSL',
    isoDigits: 2,
  ),
  lyd(
    symbol: 'LD',
    symbolNative: 'ل.د.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Dirham',
    minorPlural: 'Dirhams',
    isoNum: 434,
    isoLetters: 'LYD',
    isoDigits: 3,
  ),
  mad(
    symbol: 'DH',
    symbolNative: 'د.م.',
    decimalDigits: 2,
    majorSingle: 'Dirham',
    majorPlural: 'Dirhams',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 504,
    isoLetters: 'MAD',
    isoDigits: 2,
  ),
  mdl(
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    majorSingle: 'Leu',
    majorPlural: 'Lei',
    minorSingle: 'Ban',
    minorPlural: 'Bani',
    isoNum: 498,
    isoLetters: 'MDL',
    isoDigits: 2,
  ),
  mga(
    symbol: 'Ar',
    symbolNative: 'Ar',
    decimalDigits: 0,
    majorSingle: 'Ariary',
    majorPlural: 'Ariary',
    minorSingle: 'Iraimbilanja',
    minorPlural: 'Iraimbilanja',
    isoNum: 969,
    isoLetters: 'MGA',
    isoDigits: 2,
  ),
  mkd(
    symbol: 'den',
    symbolNative: 'ден',
    decimalDigits: 2,
    majorSingle: 'Denar',
    majorPlural: 'Denars',
    minorSingle: 'Deni',
    minorPlural: 'Deni',
    isoNum: 807,
    isoLetters: 'MKD',
    isoDigits: 2,
  ),
  mmk(
    symbol: 'Ks',
    symbolNative: 'Ks',
    decimalDigits: 2,
    majorSingle: 'Kyat',
    majorPlural: 'Kyat',
    minorSingle: 'Pya',
    minorPlural: 'Pya',
    isoNum: 104,
    isoLetters: 'MMK',
    isoDigits: 2,
  ),
  mnt(
    symbol: '₮',
    symbolNative: '₮',
    decimalDigits: 2,
    majorSingle: 'Tögrög',
    majorPlural: 'Tögrög',
    minorSingle: 'möngö',
    minorPlural: 'möngö',
    isoNum: 496,
    isoLetters: 'MNT',
    isoDigits: 2,
  ),
  mop(
    symbol: 'MOP\$',
    symbolNative: 'MOP\$',
    decimalDigits: 2,
    majorSingle: 'Pataca',
    majorPlural: 'Patacas',
    minorSingle: 'Avo',
    minorPlural: 'Avos',
    isoNum: 446,
    isoLetters: 'MOP',
    isoDigits: 2,
  ),
  mru(
    symbol: 'UM',
    symbolNative: 'أ.م.',
    decimalDigits: 0,
    majorSingle: 'Ouguiya',
    majorPlural: 'Ouguiya',
    minorSingle: 'Khoums',
    minorPlural: 'Khoums',
    isoNum: 929,
    isoLetters: 'MRU',
    isoDigits: 2,
  ),
  mur(
    symbol: 'Rs.',
    symbolNative: 'रु ',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 480,
    isoLetters: 'MUR',
    isoDigits: 2,
  ),
  mvr(
    symbol: 'MRf',
    symbolNative: '.ރ',
    decimalDigits: 2,
    majorSingle: 'Rufiyaa',
    majorPlural: 'Rufiyaa',
    minorSingle: 'laari',
    minorPlural: 'laari',
    isoNum: 462,
    isoLetters: 'MVR',
    isoDigits: 2,
  ),
  mwk(
    symbol: 'MK',
    symbolNative: 'MK',
    decimalDigits: 2,
    majorSingle: 'Kwacha',
    majorPlural: 'Kwacha',
    minorSingle: 'Tambala',
    minorPlural: 'Tambala',
    isoNum: 454,
    isoLetters: 'MWK',
    isoDigits: 2,
  ),
  mxn(
    symbol: 'MX\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 484,
    isoLetters: 'MXN',
    isoDigits: 2,
  ),
  myr(
    symbol: 'RM',
    symbolNative: 'RM',
    decimalDigits: 2,
    majorSingle: 'Ringgit',
    majorPlural: 'Ringgit',
    minorSingle: 'Sen',
    minorPlural: 'Sen',
    isoNum: 458,
    isoLetters: 'MYR',
    isoDigits: 2,
  ),
  mzn(
    symbol: 'MTn',
    symbolNative: 'MTn',
    decimalDigits: 2,
    majorSingle: 'Metical',
    majorPlural: 'Meticais',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 943,
    isoLetters: 'MZN',
    isoDigits: 2,
  ),
  nad(
    symbol: 'N\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 516,
    isoLetters: 'NAD',
    isoDigits: 2,
  ),
  ngn(
    symbol: '₦',
    symbolNative: '₦',
    decimalDigits: 2,
    majorSingle: 'Naira',
    majorPlural: 'Naira',
    minorSingle: 'Kobo',
    minorPlural: 'Kobo',
    isoNum: 566,
    isoLetters: 'NGN',
    isoDigits: 2,
  ),
  nio(
    symbol: 'C\$',
    symbolNative: 'C\$',
    decimalDigits: 2,
    majorSingle: 'Córdoba',
    majorPlural: 'Córdobas',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 558,
    isoLetters: 'NIO',
    isoDigits: 2,
  ),
  nok(
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    majorSingle: 'Krone',
    majorPlural: 'Kroner',
    minorSingle: 'Øre',
    minorPlural: 'Øre',
    isoNum: 578,
    isoLetters: 'NOK',
    isoDigits: 2,
  ),
  npr(
    symbol: 'रू',
    symbolNative: 'रू',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Paisa',
    minorPlural: 'Paisa',
    isoNum: 524,
    isoLetters: 'NPR',
    isoDigits: 2,
  ),
  nzd(
    symbol: 'NZ\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 554,
    isoLetters: 'NZD',
    isoDigits: 2,
  ),
  omr(
    symbol: 'ر.ع.',
    symbolNative: 'ر.ع.',
    decimalDigits: 3,
    majorSingle: 'Rial',
    majorPlural: 'Rials',
    minorSingle: 'Baisa',
    minorPlural: 'Baisa',
    isoNum: 512,
    isoLetters: 'OMR',
    isoDigits: 3,
  ),
  pab(
    symbol: 'B/.',
    symbolNative: 'B/.',
    decimalDigits: 2,
    majorSingle: 'Balboa',
    majorPlural: 'Balboas',
    minorSingle: 'Centésimo',
    minorPlural: 'Centésimos',
    isoNum: 590,
    isoLetters: 'PAB',
    isoDigits: 2,
  ),
  pen(
    symbol: 'S/.',
    symbolNative: 'S/.',
    decimalDigits: 2,
    majorSingle: 'Sol',
    majorPlural: 'Soles',
    minorSingle: 'Céntimo',
    minorPlural: 'Céntimos',
    isoNum: 604,
    isoLetters: 'PEN',
    isoDigits: 2,
  ),
  pgk(
    symbol: 'K',
    symbolNative: 'K',
    decimalDigits: 2,
    majorSingle: 'Kina',
    majorPlural: 'Kina',
    minorSingle: 'Toea',
    minorPlural: 'Toea',
    isoNum: 598,
    isoLetters: 'PGK',
    isoDigits: 2,
  ),
  php(
    symbol: '₱',
    symbolNative: '₱',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 608,
    isoLetters: 'PHP',
    isoDigits: 2,
  ),
  pkr(
    symbol: 'Rs.',
    symbolNative: 'Rs.',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Paisa',
    minorPlural: 'Paise',
    isoNum: 586,
    isoLetters: 'PKR',
    isoDigits: 2,
  ),
  pln(
    symbol: 'zł',
    symbolNative: 'zł',
    decimalDigits: 2,
    majorSingle: 'Złoty',
    majorPlural: 'Złote',
    minorSingle: 'Grosz',
    minorPlural: 'Groszy',
    isoNum: 985,
    isoLetters: 'PLN',
    isoDigits: 2,
  ),
  pyg(
    symbol: '₲',
    symbolNative: '₲',
    decimalDigits: 0,
    majorSingle: 'Guaraní',
    majorPlural: 'Guaraníes',
    minorSingle: 'Céntimo',
    minorPlural: 'Céntimos',
    isoNum: 600,
    isoLetters: 'PYG',
    isoDigits: 0,
  ),
  qar(
    symbol: 'QR',
    symbolNative: 'ر.ق.',
    decimalDigits: 2,
    majorSingle: 'Riyal',
    majorPlural: 'Riyals',
    minorSingle: 'Dirham',
    minorPlural: 'Dirhams',
    isoNum: 634,
    isoLetters: 'QAR',
    isoDigits: 2,
  ),
  ron(
    symbol: 'RON',
    symbolNative: 'RON',
    decimalDigits: 2,
    majorSingle: 'Leu',
    majorPlural: 'Lei',
    minorSingle: 'Ban',
    minorPlural: 'Bani',
    isoNum: 946,
    isoLetters: 'RON',
    isoDigits: 2,
  ),
  rsd(
    symbol: 'din.',
    symbolNative: 'дин.',
    decimalDigits: 2,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Para',
    minorPlural: 'Para',
    isoNum: 941,
    isoLetters: 'RSD',
    isoDigits: 2,
  ),
  rub(
    symbol: '₽',
    symbolNative: '₽',
    decimalDigits: 2,
    majorSingle: 'Ruble',
    majorPlural: 'Rubles',
    minorSingle: 'Kopek',
    minorPlural: 'Kopeks',
    isoNum: 643,
    isoLetters: 'RUB',
    isoDigits: 2,
  ),
  rwf(
    symbol: 'RF',
    symbolNative: 'RF',
    decimalDigits: 0,
    majorSingle: 'Franc',
    majorPlural: 'Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 646,
    isoLetters: 'RWF',
    isoDigits: 0,
  ),
  sar(
    symbol: 'SR',
    symbolNative: 'ر.س.',
    decimalDigits: 2,
    majorSingle: 'Riyal',
    majorPlural: 'Riyals',
    minorSingle: 'Halala',
    minorPlural: 'Halalas',
    isoNum: 682,
    isoLetters: 'SAR',
    isoDigits: 2,
  ),
  sbd(
    symbol: 'SI\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 90,
    isoLetters: 'SBD',
    isoDigits: 2,
  ),
  scr(
    symbol: 'SR',
    symbolNative: 'SR',
    decimalDigits: 2,
    majorSingle: 'Rupee',
    majorPlural: 'Rupees',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 690,
    isoLetters: 'SCR',
    isoDigits: 2,
  ),
  sdg(
    symbol: 'SDG',
    symbolNative: 'ج.س.',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Piastre',
    minorPlural: 'Piastres',
    isoNum: 938,
    isoLetters: 'SDG',
    isoDigits: 2,
  ),
  sek(
    symbol: 'kr',
    symbolNative: 'kr',
    decimalDigits: 2,
    majorSingle: 'Krona',
    majorPlural: 'Kronor',
    minorSingle: 'Öre',
    minorPlural: 'Öre',
    isoNum: 752,
    isoLetters: 'SEK',
    isoDigits: 2,
  ),
  sgd(
    symbol: 'S\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 702,
    isoLetters: 'SGD',
    isoDigits: 2,
  ),
  shp(
    symbol: '£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Penny',
    minorPlural: 'Pence',
    isoNum: 654,
    isoLetters: 'SHP',
    isoDigits: 2,
  ),
  sll(
    symbol: 'Le',
    symbolNative: 'Le',
    decimalDigits: 2,
    majorSingle: 'Leone',
    majorPlural: 'Leones',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 694,
    isoLetters: 'SLL',
    isoDigits: 2,
  ),
  sos(
    symbol: 'Sh.So.',
    symbolNative: 'Sh.So.',
    decimalDigits: 2,
    majorSingle: 'Shilling',
    majorPlural: 'Shillings',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 706,
    isoLetters: 'SOS',
    isoDigits: 2,
  ),
  srd(
    symbol: 'SR\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 968,
    isoLetters: 'SRD',
    isoDigits: 2,
  ),
  ssp(
    symbol: 'SS£',
    symbolNative: '£',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Piastre',
    minorPlural: 'Piastres',
    isoNum: 728,
    isoLetters: 'SSP',
    isoDigits: 2,
  ),
  stn(
    symbol: 'Db',
    symbolNative: 'Db',
    decimalDigits: 2,
    majorSingle: 'Dobra',
    majorPlural: 'Dobras',
    minorSingle: 'Cêntimo',
    minorPlural: 'Cêntimos',
    isoNum: 930,
    isoLetters: 'STN',
    isoDigits: 2,
  ),
  svc(
    symbol: '₡',
    symbolNative: '₡',
    decimalDigits: 2,
    majorSingle: 'Colón',
    majorPlural: 'Colones',
    minorSingle: 'Centavo',
    minorPlural: 'Centavos',
    isoNum: 222,
    isoLetters: 'SVC',
    isoDigits: 2,
  ),
  syp(
    symbol: 'S£',
    symbolNative: 'ل.س.',
    decimalDigits: 2,
    majorSingle: 'Pound',
    majorPlural: 'Pounds',
    minorSingle: 'Piastre',
    minorPlural: 'Piastres',
    isoNum: 760,
    isoLetters: 'SYP',
    isoDigits: 2,
  ),
  szl(
    symbol: 'L',
    symbolNative: 'L',
    decimalDigits: 2,
    majorSingle: 'Lilangeni',
    majorPlural: 'Emalangeni',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 748,
    isoLetters: 'SZL',
    isoDigits: 2,
  ),
  thb(
    symbol: '฿',
    symbolNative: '฿',
    decimalDigits: 2,
    majorSingle: 'Baht',
    majorPlural: 'Baht',
    minorSingle: 'Satang',
    minorPlural: 'Satang',
    isoNum: 764,
    isoLetters: 'THB',
    isoDigits: 2,
  ),
  tjs(
    symbol: 'SM',
    symbolNative: 'SM',
    decimalDigits: 2,
    majorSingle: 'Somoni',
    majorPlural: 'Somoni',
    minorSingle: 'Diram',
    minorPlural: 'Diram',
    isoNum: 972,
    isoLetters: 'TJS',
    isoDigits: 2,
  ),
  tmt(
    symbol: 'T',
    symbolNative: 'T',
    decimalDigits: 2,
    majorSingle: 'Manat',
    majorPlural: 'Manat',
    minorSingle: 'Tenge',
    minorPlural: 'Tenge',
    isoNum: 934,
    isoLetters: 'TMT',
    isoDigits: 2,
  ),
  tnd(
    symbol: 'DT',
    symbolNative: 'د.ت.',
    decimalDigits: 3,
    majorSingle: 'Dinar',
    majorPlural: 'Dinars',
    minorSingle: 'Millime',
    minorPlural: 'Millimes',
    isoNum: 788,
    isoLetters: 'TND',
    isoDigits: 3,
  ),
  top(
    symbol: 'T\$',
    symbolNative: 'T\$',
    decimalDigits: 2,
    majorSingle: 'Pa\'anga',
    majorPlural: 'Pa\'anga',
    minorSingle: 'Seniti',
    minorPlural: 'Seniti',
    isoNum: 776,
    isoLetters: 'TOP',
    isoDigits: 2,
  ),
  try_(
    symbol: '₺',
    symbolNative: '₺',
    decimalDigits: 2,
    majorSingle: 'Lira',
    majorPlural: 'Lira',
    minorSingle: 'Kuruş',
    minorPlural: 'Kuruş',
    isoNum: 949,
    isoLetters: 'TRY',
    isoDigits: 2,
  ),
  ttd(
    symbol: 'TT\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 780,
    isoLetters: 'TTD',
    isoDigits: 2,
  ),
  twd(
    symbol: 'NT\$',
    symbolNative: 'NT\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 901,
    isoLetters: 'TWD',
    isoDigits: 2,
  ),
  tzs(
    symbol: 'TSh',
    symbolNative: 'TSh',
    decimalDigits: 2,
    majorSingle: 'Shilling',
    majorPlural: 'Shillings',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 834,
    isoLetters: 'TZS',
    isoDigits: 2,
  ),
  uah(
    symbol: '₴',
    symbolNative: '₴',
    decimalDigits: 2,
    majorSingle: 'Hryvnia',
    majorPlural: 'Hryvnias',
    minorSingle: 'Kopiyka',
    minorPlural: 'Kopiykas',
    isoNum: 980,
    isoLetters: 'UAH',
    isoDigits: 2,
  ),
  ugx(
    symbol: 'USh',
    symbolNative: 'USh',
    decimalDigits: 0,
    majorSingle: 'Shilling',
    majorPlural: 'Shillings',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 800,
    isoLetters: 'UGX',
    isoDigits: 0,
  ),
  uyu(
    symbol: '\$U',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Peso',
    majorPlural: 'Pesos',
    minorSingle: 'Centésimo',
    minorPlural: 'Centésimos',
    isoNum: 858,
    isoLetters: 'UYU',
    isoDigits: 2,
  ),
  uzs(
    symbol: 'so\'m',
    symbolNative: 'so\'m',
    decimalDigits: 2,
    majorSingle: 'So\'m',
    majorPlural: 'So\'m',
    minorSingle: 'Tiyin',
    minorPlural: 'Tiyin',
    isoNum: 860,
    isoLetters: 'UZS',
    isoDigits: 2,
  ),
  ves(
    symbol: 'Bs.S',
    symbolNative: 'Bs.S',
    decimalDigits: 2,
    majorSingle: 'Bolívar',
    majorPlural: 'Bolívares',
    minorSingle: 'Céntimo',
    minorPlural: 'Céntimos',
    isoNum: 928,
    isoLetters: 'VES',
    isoDigits: 2,
  ),
  vnd(
    symbol: '₫',
    symbolNative: '₫',
    decimalDigits: 0,
    majorSingle: 'Dong',
    majorPlural: 'Dong',
    minorSingle: 'Hào',
    minorPlural: 'Hào',
    isoNum: 704,
    isoLetters: 'VND',
    isoDigits: 0,
  ),
  vuv(
    symbol: 'VT',
    symbolNative: 'VT',
    decimalDigits: 0,
    majorSingle: 'Vatu',
    majorPlural: 'Vatu',
    minorSingle: '',
    minorPlural: '',
    isoNum: 548,
    isoLetters: 'VUV',
    isoDigits: 0,
  ),
  wst(
    symbol: 'WS\$',
    symbolNative: 'T',
    decimalDigits: 2,
    majorSingle: 'Tala',
    majorPlural: 'Tala',
    minorSingle: 'Sene',
    minorPlural: 'Sene',
    isoNum: 882,
    isoLetters: 'WST',
    isoDigits: 2,
  ),
  xaf(
    symbol: 'FCFA',
    symbolNative: 'FCFA',
    decimalDigits: 0,
    majorSingle: 'CFA Franc',
    majorPlural: 'CFA Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 950,
    isoLetters: 'XAF',
    isoDigits: 0,
  ),
  xcd(
    symbol: 'EC\$',
    symbolNative: '\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 951,
    isoLetters: 'XCD',
    isoDigits: 2,
  ),
  xof(
    symbol: 'CFA',
    symbolNative: 'CFA',
    decimalDigits: 0,
    majorSingle: 'CFA Franc',
    majorPlural: 'CFA Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 952,
    isoLetters: 'XOF',
    isoDigits: 0,
  ),
  xpf(
    symbol: 'CFPF',
    symbolNative: 'F',
    decimalDigits: 0,
    majorSingle: 'CFP Franc',
    majorPlural: 'CFP Francs',
    minorSingle: 'Centime',
    minorPlural: 'Centimes',
    isoNum: 953,
    isoLetters: 'XPF',
    isoDigits: 0,
  ),
  yer(
    symbol: 'YR',
    symbolNative: 'ر.ي.',
    decimalDigits: 2,
    majorSingle: 'Rial',
    majorPlural: 'Rials',
    minorSingle: 'Fils',
    minorPlural: 'Fils',
    isoNum: 886,
    isoLetters: 'YER',
    isoDigits: 2,
  ),
  zar(
    symbol: 'R',
    symbolNative: 'R',
    decimalDigits: 2,
    majorSingle: 'Rand',
    majorPlural: 'Rand',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 710,
    isoLetters: 'ZAR',
    isoDigits: 2,
  ),
  zmw(
    symbol: 'ZK',
    symbolNative: 'ZK',
    decimalDigits: 2,
    majorSingle: 'Kwacha',
    majorPlural: 'Kwacha',
    minorSingle: 'Ngwee',
    minorPlural: 'Ngwee',
    isoNum: 967,
    isoLetters: 'ZMW',
    isoDigits: 2,
  ),
  zwl(
    symbol: 'Z\$',
    symbolNative: 'Z\$',
    decimalDigits: 2,
    majorSingle: 'Dollar',
    majorPlural: 'Dollars',
    minorSingle: 'Cent',
    minorPlural: 'Cents',
    isoNum: 932,
    isoLetters: 'ZWL',
    isoDigits: 2,
  ),
  unknown(
    symbol: '',
    symbolNative: '',
    decimalDigits: 0,
    majorSingle: '',
    majorPlural: '',
    minorSingle: '',
    minorPlural: '',
    isoNum: 0,
    isoLetters: '',
    isoDigits: 0,
  );

  const Currency({
    required this.symbol,
    required this.symbolNative,
    required this.decimalDigits,
    required this.majorSingle,
    required this.majorPlural,
    required this.minorSingle,
    required this.minorPlural,
    required this.isoNum,
    required this.isoLetters,
    required this.isoDigits,
  });

  factory Currency.fromIsoLetters(
    String isoLetters, {
    bool returnUnknown = true,
  }) {
    try {
      return Currency.values.firstWhere(
        (currency) => currency.isoLetters == isoLetters,
      );
    } catch (e) {
      if (returnUnknown) {
        return Currency.unknown;
      }
      rethrow;
    }
  }

  factory Currency.fromIsoNum(String isoNum, {bool returnUnknown = true}) {
    try {
      return Currency.values.firstWhere(
        (currency) => currency.isoNum.toString() == isoNum,
      );
    } catch (e) {
      if (returnUnknown) {
        return Currency.unknown;
      }
      rethrow;
    }
  }

  static Currency? tryFromIsoLetters(String? isoLetters) {
    try {
      if (isoLetters == null) return null;
      return Currency.fromIsoLetters(isoLetters, returnUnknown: false);
    } catch (e) {
      return null;
    }
  }

  static Currency? tryFromIsoNum(String isoNum) {
    try {
      return Currency.fromIsoNum(isoNum, returnUnknown: false);
    } catch (e) {
      return null;
    }
  }

  final String symbol;
  final String symbolNative;
  final int decimalDigits;
  final String majorSingle;
  final String majorPlural;
  final String minorSingle;
  final String minorPlural;
  final int isoNum;
  final String isoLetters;
  final int isoDigits;
}

extension CurrencyFormatterExt on Currency {
  String format(double amount) {
    return CurrencyFormatter.format(
      amount / pow(10, decimalDigits),
      _settings,
      decimal: decimalDigits,
    );
  }

  CurrencyFormat get _settings => CurrencyFormat(
    symbol: symbolNative,
    decimalSeparator: '.',
    thousandSeparator: ',',
  );
}
